### PR TITLE
rename namespace of boxy tasks.

### PR DESCRIPTION
**Pull request by RahulMahale**

### CODE REVIEW

**Comment by RahulMahale** [comment]
Updated all the custom boxy-cap tasks under `boxy` namespace and deployed on lab2-staging and deployment worked after modifying tasks name in `deploy.rb`

selection_089

@neerajdotname _a please review.

**Comment by neerajdotname** [comment]
@RahulMahale in many files the indentation is not right. Please fix it.

**Comment by RahulMahale** [comment]
Done.

**Comment by neerajdotname** [comment]
@RahulMahale Please release a new version of this gem.

**Comment by vijayagrawal18** [comment]
@RahulMahale _a pl update README.

**Pull request merged**
