### PR TITLE
keep old db backups for 90 days

### PR DESCRIPTION
**Pull request by RahulMahale**
As of now only last 5 db backups are retained rest are deleted, need to modify recipe to keep old db backups for 90 days

### CODE REVIEW

**Comment by RahulMahale** [comment]
@neerajdotname _a

**Comment by vipulnsward** [comment]
This should be configurable and not fixed. Not every project needs 90 day retention and on small staging servers with many deployments, it can make the server run out of space.
The original change, was to handle this scenario, since we were running out of space on a server due to this.

**Comment by RahulMahale** [comment]
Agreed, We have variable `set :keep_releases, 5`  in `config/deploy.rb` which is fetched further to keep number of dumps, but changing value of this variable will also affect the releases to keep same number of releases in application directory '/data/apps/<app_name>/releases'

Adding similar kind of variable specific to dump rotation may affect all the other projects and we will have to add that variable in `config/deploy.rb` of each project.

Alternate approach:-

I would suggest to write a simple cron script which takes daily db backup at midnight and stores it in some custom location

**Comment by neerajdotname** [comment]
> I would suggest to write a simple cron script which takes daily db backup at midnight and stores it in some custom location

This issue is not about taking daily backups. This issue is about the backups which are created by anymeans should not be deleted before 90 days.

@RahulMahale _a

**Comment by RahulMahale** [comment]
@neerajdotname This PR has the change to keep db backups for 90 days

**Comment by neerajdotname** [comment]
As vipul mentioned we should have it configurable. Is it configurable yet.

**Comment by RahulMahale** [comment]
No it isnt configurable yet, will push the change for it here and in boxy as well, but the concern would be that it may affect all the other projects using boxy-cap, to avoid this we will have to add the configurable  variable in config/deploy.rb of each project if it uses the latest boxy-cap.

Will come up with some work around.

**Comment by neerajdotname** [comment]
No need to come up with a workaround.

This will be an issue only when a repo upgrades boxy-cap. When a repo upgrades they should do the right thing. Let's keep it simple.

**Comment by RahulMahale** [comment]
Ok sure, will do the change accordingly.

**Comment by RahulMahale** [comment]
some how variable change is not working on server, will debug more into it.

**Comment by RahulMahale** [comment]
Fixed it, we can set the days to retain the logs in config/deploy.rb by adding variable `set :db_dump_retention, 90`
`
tested it on lab4 staging server and it is working.

**Comment by RahulMahale** [comment]
@neerajdotname _a

**Pull request merged**
