### PR TITLE
Fix spelling of revision through this repository

### PR DESCRIPTION
**Pull request by RahulMahale**
https://monosnap.com/file/G9GzHysDcflSE1F3wUc0KY5b9W5RMl.png

@RahulMahale _a

### CODE REVIEW

**Comment by RahulMahale** [comment]
@ershad please check, deployment is failing with this error https://gist.github.com/RahulMahale/defcf84653d2e3e90bc7d57f9e2a99f2

I have just added a simple cap task `logs:revision` similar to others but its not working.
We are unable to deploy due to this error.

**Comment by prathamesh-sonpatki** [comment]
@RahulMahale Just remove https://github.com/bigbinary/boxy-cap/blob/master/lib/boxy-cap/revision.rb#L1 this line and it will work.

**Comment by RahulMahale** [comment]
Ok, Thanks @prathamesh-sonpatki

**Comment by ershad** [comment]
@RahulMahale _a please try that.
@prathamesh-sonpatki what amuses me is the same line before he modified the file - https://github.com/bigbinary/boxy-cap/pull/15/files#diff-ebcdb624bac12bc931fa3068a698bf74L1 . Not really sure how it worked before.

**Comment by prathamesh-sonpatki** [comment]
It never worked

**Comment by ershad** [comment]
True, now that makes sense.

**Comment by RahulMahale** [comment]
fixed in #16.

**Pull request merged**
